language: node_js
node_js:
- 8.4.0
sudo: required
services:
- docker
- postgresql-9.6
sudo: true
before_script:
- npm run build
- psql -c 'create database inventory;' -U postgres
- sudo apt-get install postgresql-9.6-postgis-2.3
- psql -U postgres -c 'CREATE EXTENSION postgis;' -d inventory
- npm run build:db
script: node ./service/build/server/index.js & npm run test
deploy:
  provider: script
  script: docker login -u $DOCKER_LOGIN -p $DOCKER_PW && docker-compose build && docker push katm201/rideshare:latest
  on:
    branch: master
