language: node_js
node_js:
- 8.4.0
sudo: required
services:
- docker
before_script:
- npm run build
script: node ./service/build/server/index.js & npm run test
after_success: 
- docker login -u $DOCKER_LOGIN -p $DOCKER_PW
- docker-compose build
- docker push katm201/rideshare:latest
