language: node_js
node_js:
- 8.4.0
sudo: required
services:
- docker
- postgresql
- postgis
before_script:
- npm run build
- psql -c 'create database inventory;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -d inventory
- npm run build:db
script: node ./service/build/server/index.js & npm run test
deploy:
  provider: script
  script: docker login -u $DOCKER_LOGIN -p $DOCKER_PW && docker-compose build && docker push katm201/rideshare:latest
  on:
    branch: master
