language: node_js
node_js:
- 9.3.0
sudo: required
services:
- docker
- redis
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
sudo: true
before_script:
- psql -c 'create database inventory;' -U postgres
- psql -U postgres -c 'CREATE EXTENSION postgis;' -d inventory
- npm run db:build
deploy:
  provider: script
  script: docker login -u $DOCKER_LOGIN -p $DOCKER_PW && docker-compose build && docker push katm201/rideshare:latest
  on:
    branch: master
