language: node_js
node_js:
- 8.4.0
sudo: required
services:
- docker
- postgresql
before_script:
- npm run build
- psql -c 'create database inventory;' -U postgres
- npm run db:setup
script: node ./service/build/server/index.js & npm run test
deploy:
  provider: script
  script: docker login -u $DOCKER_LOGIN -p $DOCKER_PW && docker-compose build && docker push katm201/rideshare:latest
  on:
    branch: master
